name: Publish Rouge Theme
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - name: Build themes
        run: yarn build
      - name: Publish theme
        run: yarn vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      - name: Update VSIX
        run: |
          git mv *.vsix .archive/
          yarn vsce package
          changed=$(git status --porcelain)
          if [[ -n "$changed" ]]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'josefaidt@users.noreply.github.com'
            if [[ ! `git diff --quiet HEAD -- *.vsix` ]]; then
              git add *.vsix
              git commit -m "[automated] update package"
            fi
            git push
          fi